# Generated by Django 3.0.8 on 2020-08-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('S', 'Staples'), ('SB', 'Snacks and Branded Food'), ('B', 'Beverages'), ('PC', 'Personal Care'), ('HC', 'Home Care'), ('BC', 'Baby Care')], max_length=2),
        ),
    ]
