# Generated by Django 3.0.8 on 2020-08-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='consumer_price',
        ),
        migrations.AddField(
            model_name='product',
            name='wholesaler_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
