# Generated by Django 3.0.8 on 2020-10-18 12:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0019_auto_20201018_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Product_Request',
        ),
    ]
