# Generated by Django 3.0.8 on 2020-10-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_product_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_request',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
