# Generated by Django 3.0.8 on 2020-10-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20201018_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_request',
            name='time',
            field=models.DateTimeField(default=None),
        ),
    ]
