# Generated by Django 3.0.8 on 2020-10-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20201018_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_request',
            old_name='time',
            new_name='request_time',
        ),
    ]
