# Generated by Django 3.0.8 on 2020-10-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20201018_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_request',
            old_name='request_time',
            new_name='product_request_time',
        ),
    ]
