# Generated by Django 3.0.8 on 2020-10-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20201018_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='received_order',
            name='address',
            field=models.TextField(default=None),
        ),
    ]
