# Generated by Django 3.0.8 on 2020-10-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20201018_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='received_order',
            name='receiving_time',
            field=models.DateTimeField(default=None),
        ),
    ]
